# Generated by Django 5.1.4 on 2026-03-03 16:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('KE', 'Kenya'), ('UG', 'Uganda'), ('TZ', 'Tanzania'), ('ZM', 'Zambia')], max_length=3, unique=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(message='Only numbers, letters, underscores, dashes and spaces are allowed. Remove new lines, tabs, commas, fullstops if any and use - or _ instead.', regex='^[a-zA-Z0-9-_: ]+$')])),
                ('provider', models.CharField(choices=[('MPESA-C2B', 'MPESA-C2B'), ('MPESA-B2C', 'MPESA-B2C'), ('MPESA-B2B', 'MPESA-B2B')], max_length=20)),
                ('currency', models.CharField(blank=True, choices=[('KES', 'KES')], help_text='Required for XB payments', max_length=3, null=True)),
                ('country', models.CharField(choices=[('KE', 'Kenya'), ('UG', 'Uganda'), ('TZ', 'Tanzania'), ('ZM', 'Zambia')], max_length=3)),
                ('tarrif_type', models.CharField(choices=[('PERCENTAGE', 'PERCENTAGE'), ('TIERED', 'TIERED')], max_length=20)),
                ('default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_percentage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tarrif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='pricing.pricingplan')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarrifs', to='user_accounts.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='pricing.pricingplan')),
            ],
            options={
                'verbose_name': 'Tarrif',
                'unique_together': {('plan', 'business')},
            },
        ),
    ]
