# Generated by Django 5.1.4 on 2026-08-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payins', '0006_depositrequest_wallet_credited'),
        ('payouts', '0001_initial'),
        ('pricing', '0001_initial'),
        ('user_accounts', '0003_userprofile_must_change_password_loginotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.SlugField(help_text='Limit identifier e.g low-risk', unique=True)),
                ('currency', models.CharField(choices=[('KES', 'KES')], max_length=3)),
                ('collection_amount_per_txn', models.DecimalField(decimal_places=2, max_digits=11)),
                ('disbursement_amount_per_txn', models.DecimalField(decimal_places=2, max_digits=11)),
                ('disbursement_amount_per_day', models.DecimalField(decimal_places=2, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account Limit',
            },
        ),
        migrations.CreateModel(
            name='BusinessAccountLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_limit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_account_limits', to='pricing.accountlimits')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_limits', to='user_accounts.business')),
            ],
            options={
                'verbose_name': 'Business Account Limit',
            },
        ),
        migrations.CreateModel(
            name='ProviderCostPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MPESA-C2B', 'MPESA-C2B'), ('MPESA-B2C', 'MPESA-B2C'), ('MPESA-B2B', 'MPESA-B2B')], max_length=20)),
                ('currency', models.CharField(choices=[('KES', 'KES')], default='KES', max_length=3)),
                ('country', models.CharField(choices=[('KE', 'Kenya'), ('UG', 'Uganda'), ('TZ', 'Tanzania'), ('ZM', 'Zambia')], default='KE', max_length=3)),
                ('is_free', models.BooleanField(default=False, help_text='No cost tiers needed - always 0 (e.g. MPESA-C2B)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider Cost Plan',
                'unique_together': {('provider', 'currency', 'country')},
            },
        ),
        migrations.CreateModel(
            name='ProviderCostTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='pricing.providercostplan')),
            ],
            options={
                'verbose_name': 'Provider Cost Tier',
            },
        ),
        migrations.CreateModel(
            name='TransactionMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PAYIN', 'PAYIN'), ('PAYOUT', 'PAYOUT')], max_length=7)),
                ('provider', models.CharField(choices=[('MPESA-C2B', 'MPESA-C2B'), ('MPESA-B2C', 'MPESA-B2C'), ('MPESA-B2B', 'MPESA-B2B')], max_length=20)),
                ('currency', models.CharField(choices=[('KES', 'KES')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The transaction amount', max_digits=20)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, help_text='What we charged the business', max_digits=10)),
                ('provider_cost', models.DecimalField(decimal_places=2, default=0, help_text='What the provider charged us', max_digits=10)),
                ('margin', models.DecimalField(decimal_places=2, default=0, help_text='revenue - provider_cost', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_margins', to='user_accounts.business')),
                ('deposit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='margin', to='payins.depositrequest')),
                ('payout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='margin', to='payouts.payoutrequest')),
            ],
            options={
                'verbose_name': 'Transaction Margin',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('deposit__isnull', False), ('payout__isnull', True)), models.Q(('deposit__isnull', True), ('payout__isnull', False)), _connector='OR'), name='margin_exactly_one_of_deposit_or_payout')],
            },
        ),
    ]
