# Generated by Django 5.1.4 on 2026-03-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0002_businesscallback_is_active_whitelistedip'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbacklog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='businesscallback',
            name='alias_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callbacklog',
            name='alias_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callbacklog',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='businesscallback',
            unique_together={('business', 'event_type')},
        ),
    ]
