"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import sentry_sdk

sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN"),
    # Add data like request headers and IP for users,
    # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
    send_default_pii=True,
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
HASH_ID_SECRET = SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.environ.get("DEBUG") == 'True' else False
ENVIRONMENT = os.environ.get("ENVIRONMENT", "dev")

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS").split(",") if os.environ.get("ALLOWED_HOSTS") else []

# Django sits behind nginx/Cloudflare, which terminate TLS and forward plain HTTP -
# without this, request.is_secure() is always False, breaking CSRF origin checks
# and secure cookies.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "corsheaders",
    "django_filters",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_countries",
    "django_tables2",
    "drf_spectacular",

    "user_accounts",
    "dashboard",
    "payins",
    "payouts",
    "callbacks",
    "pricing",
    "wallet",
    "landing",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    "user_accounts.middlewares.TimezoneMiddleware",
    "user_accounts.middlewares.EnforceInactivityLogoutMiddleware",
    "user_accounts.middlewares.PreventConcurrentLoginsMiddleware",
    "user_accounts.middlewares.MultisiteAccountHandler",
    "user_accounts.middlewares.ForcePasswordChangeMiddleware",
]

# Force-logout dashboard sessions after this many seconds of inactivity (live environment only).
INACTIVITY_LOGOUT_SECONDS = 30 * 60

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

if ENVIRONMENT == "live":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": os.environ.get("DB_NAME"),
            "USER": os.environ.get("DB_USER"),
            "PASSWORD": os.environ.get("DB_PASSWORD"),
            "HOST": os.environ.get("DB_HOST"),
            "PORT": os.environ.get("DB_PORT"),
        }
    }

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
REDIS_URL= os.environ.get("REDIS_URL", "redis://localhost:6379/1")

CACHES = {
    "default": {
        # 'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        # 'LOCATION': os.path.join(BASE_DIR, 'cache'),
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_KEEPALIVE": True,
            "SOCKET_TIMEOUT": 5,
        },
    },
    "locks": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get(
            "REDIS_LOCK_URL", os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1")
        ),
        "OPTIONS": {
            "CONNECTION_POOL_KWARGS": {
                "max_connections": int(
                    os.environ.get("REDIS_LOCK_MAX_CONNECTIONS", 50)
                ),
            }
        },
    },
}

CELERY_TASK_LOCK_CACHE = "locks"
CELERY_TASK_LOCK_EXPIRY = int(os.environ.get("CELERY_TASK_LOCK_EXPIRY", 60 * 30))

LOGIN_URL = "/login/"

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "public"),
]
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'public')
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

if ENVIRONMENT == "live":
    STATIC_ROOT = os.environ.get("STATIC_ROOT")
    MEDIA_ROOT = os.environ.get("MEDIA_ROOT")


APP_URL = os.environ.get("APP_URL")
FRONTEND_URL = os.environ.get("FRONTEND_URL", APP_URL)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "COERCE_DECIMAL_TO_STRING": True,
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "authentications.APITokenAuthentication",
        # "rest_framework_simplejwt.authentication.JWTAuthentication",
        # "rest_framework.authentication.BasicAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "30/min",
        "user": "100/min",
        "mnos": "10000/min",
        "burst": "1500/min",
        "checkout": "45/min",
        "email": "10/hour",
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Kizuka Core API",
    "DESCRIPTION": "Kizuka Core APIs Documentation",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # The BearerAuth scheme itself is now provided by APITokenAuthenticationScheme
    # (authentications.py), a proper OpenApiAuthenticationExtension - it's derived
    # automatically per-view from authentication_classes. The SECURITY_DEFINITIONS/
    # SECURITY keys used to live here, but drf_spectacular doesn't recognize either
    # key (they're a drf_yasg-ism), so they silently did nothing on their own; once
    # the extension started working, redeclaring "BearerAuth" here just duplicated
    # the same requirement on every endpoint.
}

# JWT SETTINGS
JWT_STANDARD_EXPIRY = int(os.environ.get("JWT_STANDARD_EXPIRY", 600))

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=3),
}

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = os.environ.get("CORS_ALLOWED_ORIGINS").split(",")
CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS").split(",")
# CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "Set-Cookie"
)

OUTWARD_REQUEST_PROXY = os.environ.get(
    "OUTWARD_REQUEST_PROXY", "https://outward-proxy.playpark.com"
)

OUTWARD_REQUEST_HEADERS = {
    "Content-Type": "application/json",
    "User-Agent": "_",
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
if ENVIRONMENT != 'live':
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = os.environ.get("EMAIL_PORT")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS") == 'True'
EMAIL_USE_SSL = not EMAIL_USE_TLS
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")

# Recipient for payout stuck-in-review alerts (PayoutRequest.flag_for_review) - sent via
# the Zoho Mail API, not EMAIL_BACKEND above. No default: unset means the alert is skipped.
PAYOUT_REVIEW_ALERT_EMAIL = os.environ.get("PAYOUT_REVIEW_ALERT_EMAIL")


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "error.log",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "level": "ERROR",
            "propagate": True,
        },
        "django": {
            "handlers": ["file"],
            "level": "WARNING",
            "propagate": True,
        },
    },
}

# MPESA SETTINGS
MPESA_BASE_API_URL = os.environ.get("MPESA_BASE_API_URL", "https://api.safaricom.co.ke")

# MPESA C2B SETTINGS
MPESA_SHORTCODE = os.environ.get("MPESA_SHORTCODE")
MPESA_PASSKEY = os.environ.get("MPESA_PASSKEY")
MPESA_CONSUMER_SECRET = os.environ.get("MPESA_CONSUMER_SECRET")
MPESA_CONSUMER_KEY = os.environ.get("MPESA_CONSUMER_KEY")
MPESA_PARTY_B = os.environ.get("MPESA_PARTY_B", MPESA_SHORTCODE)
MPESA_TRANS_TYPE= os.environ.get("MPESA_TRANS_TYPE", "CustomerPayBillOnline")

# MPESA B2C SETTINGS
B2C_SHORTCODE = os.environ.get("MPESA_B2C_SHORTCODE")
B2C_CONSUMER_KEY = os.environ.get("MPESA_B2C_CONSUMER_KEY")
B2C_CONSUMER_SECRET = os.environ.get("MPESA_B2C_CONSUMER_SECRET")
B2C_INITIATOR_NAME = os.environ.get("MPESA_B2C_INITIATOR_NAME")
B2C_INITIATOR_PASSWORD = os.environ.get("MPESA_B2C_INITIATOR_PASSWORD")

HAKIKISHA_CONSUMER_KEY = os.environ.get("MPESA_B2C_CONSUMER_KEY")
HAKIKISHA_SECRET = os.environ.get("MPESA_B2C_CONSUMER_SECRET")
HAKIKISHA_BASE_URL = MPESA_BASE_API_URL

# Zoho Settings
ZOHO_CLIENT_ID = os.environ.get("ZOHO_CLIENT_ID")
ZOHO_CLIENT_SECRET = os.environ.get("ZOHO_CLIENT_SECRET")
ZOHO_REFRESH_TOKEN = os.environ.get("ZOHO_REFRESH_TOKEN")
ZOHO_ACCOUNT_ID = os.environ.get("ZOHO_ACCOUNT_ID")
