# Generated by Django 5.1.4 on 2026-03-03 16:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', editable=False, max_length=20)),
                ('country', models.CharField(choices=[('KE', 'Kenya'), ('UG', 'Uganda'), ('TZ', 'Tanzania'), ('ZM', 'Zambia')], default='KE', max_length=3)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only numbers is required. Remove space and any other non-numeric character', regex='^([\\s\\d]+)$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Only numbers, letters, underscores, dashes and spaces are allowed. Remove new lines, tabs, commas, fullstops if any and use - or _ instead.', regex='^[a-zA-Z0-9-_: ]+$')])),
                ('narration', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Only numbers, letters, underscores, dashes and spaces are allowed. Remove new lines, tabs, commas, fullstops if any and use - or _ instead.', regex='^[a-zA-Z0-9-_: ]+$')])),
                ('init_response', models.JSONField(blank=True, null=True)),
                ('stk_response', models.JSONField(blank=True, null=True)),
                ('callback_response', models.JSONField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, choices=[('MPESA-C2B', 'MPESA-C2B'), ('MPESA-B2C', 'MPESA-B2C'), ('MPESA-B2B', 'MPESA-B2B')], max_length=20, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Only numbers, letters, underscores, dashes and spaces are allowed. Remove new lines, tabs, commas, fullstops if any and use - or _ instead.', regex='^[a-zA-Z0-9-_: ]+$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_requests', to='user_accounts.business')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
