# Generated by Django 5.1.4 on 2026-03-04 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Only numbers, letters, underscores, dashes and spaces are allowed. Remove new lines, tabs, commas, fullstops if any and use - or _ instead.', regex='^[a-zA-Z0-9-_: ]+$')]),
        ),
    ]
