# Generated by Django 5.1.4 on 2026-03-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payins', '0002_depositrequest_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
