# Generated by Django 5.1.4 on 2026-03-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payins', '0003_depositrequest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='currency',
            field=models.CharField(choices=[('KES', 'KES')], default='KES', max_length=3),
        ),
    ]
