# Generated by Django 5.1.4 on 2026-03-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payins', '0004_depositrequest_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='provider',
            field=models.CharField(blank=True, choices=[('MPESA-C2B', 'MPESA-C2B')], max_length=20, null=True),
        ),
    ]
