# Generated by Django 5.1.4 on 2026-03-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payins', '0005_alter_depositrequest_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='wallet_credited',
            field=models.BooleanField(default=False),
        ),
    ]
