# Generated by Django 5.1.4 on 2026-03-03 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.CharField(blank=True, max_length=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('can_withdraw', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='user_accounts.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trans_type', models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('PAYOUT', 'PAYOUT'), ('REFUND', 'REFUND'), ('WITHDRAWAL', 'WITHDRAWAL'), ('FEE', 'FEE'), ('TAX', 'TAX'), ('ADJUSTMENT', 'ADJUSTMENT')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
