# Generated by Django 5.1.4 on 2026-03-04 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling')], default='KES', max_length=3),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='user_accounts.business'),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('business', 'currency')},
        ),
    ]
