# Generated by Django 5.1.4 on 2026-03-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('wallet', 'reference')},
        ),
    ]
