# Generated by Django 5.1.4 on 2026-03-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling')], default='KES', max_length=3),
        ),
    ]
