# Generated by Django 5.1.4 on 2026-03-09 10:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(choices=[('KE', 'Kenya'), ('UG', 'Uganda'), ('TZ', 'Tanzania'), ('ZM', 'Zambia')], default='KE', max_length=3)),
                ('currency', models.CharField(choices=[('KES', 'KES')], default='KES', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Only numbers, letters, underscores, dashes and spaces are allowed. Remove new lines, tabs, commas, fullstops if any and use - or _ instead.', regex='^[a-zA-Z0-9-_: ]+$')])),
                ('narration', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Only numbers, letters, underscores, dashes and spaces are allowed. Remove new lines, tabs, commas, fullstops if any and use - or _ instead.', regex='^[a-zA-Z0-9-_: ]+$')])),
                ('provider', models.CharField(blank=True, choices=[('MPESA-B2C', 'MPESA-B2C'), ('MPESA-B2B', 'MPESA-B2B')], max_length=20, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Only numbers, letters, underscores, dashes and spaces are allowed. Remove new lines, tabs, commas, fullstops if any and use - or _ instead.', regex='^[a-zA-Z0-9-_: ]+$')])),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_id_2', models.CharField(blank=True, max_length=100, null=True)),
                ('init_response', models.JSONField(blank=True, null=True)),
                ('callback_response', models.JSONField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('IN_REVIEW', 'IN REVIEW'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to='user_accounts.business')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
