# Generated by Django 5.1.4 on 2026-08-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='query_tracking_id',
            field=models.CharField(blank=True, help_text='OriginatorConversationID of the most recent TransactionStatusQuery sent for this payout', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='query_tracking_id_2',
            field=models.CharField(blank=True, help_text='ConversationID of the most recent TransactionStatusQuery sent for this payout', max_length=100, null=True),
        ),
    ]
