# Generated by Django 5.1.4 on 2026-02-27 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('api_key', models.TextField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_reset_token_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('password_reset_requested_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('password_reset_used', models.BooleanField(default=False)),
                ('invite_token_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('invite_requested_at', models.DateTimeField(blank=True, null=True)),
                ('invite_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.CharField(blank=True, max_length=10, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='user_accounts.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Team Member',
                'verbose_name_plural': 'Business Team Members',
                'unique_together': {('business', 'user')},
            },
        ),
        migrations.CreateModel(
            name='InviteUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('invited', 'User Invited'), ('activation_successful', 'Account Activated'), ('activation_failed', 'Activation Failed'), ('invitation_declined', 'Invitation Declined'), ('token_expired', 'Token Expired'), ('token_already_used', 'Token Already Used'), ('invalid_token', 'Invalid Token')], max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_logs', to='user_accounts.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invite User Log',
                'verbose_name_plural': 'Invite User Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'business', '-created_at'], name='user_accoun_user_id_972cde_idx'), models.Index(fields=['ip_address', '-created_at'], name='user_accoun_ip_addr_54e167_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('requested', 'Reset Requested'), ('reset_successful', 'Reset Successful'), ('reset_failed', 'Reset Failed'), ('token_expired', 'Token Expired'), ('token_already_used', 'Token Already Used'), ('invalid_token', 'Invalid Token')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Log',
                'verbose_name_plural': 'Password Reset Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_accoun_user_id_1a0ab1_idx'), models.Index(fields=['ip_address', '-created_at'], name='user_accoun_ip_addr_c15de3_idx')],
            },
        ),
    ]
